src/__init__.py
import os
from flask import Flask

# CSV 파일 경로와 임시 파일 경로입니다.
CSV_FILEPATH = os.path.join(os.getcwd(), __name__, 'users.csv') 
TMP_FILEPATH = os.path.join(os.getcwd(), __name__, 'tmp.csv') 

def create_app(config=None):
    """
    create_app 은 애플리케이션 팩토리 패턴에 따른 함수입니다.

    config 파라미터는 테스트에 필요하니 변경하지는 말아주세요!
    """
    app = Flask(__name__)
    
    # 여기에서 주어진 config 에 따라 추가 설정을 합니다.
    if config is not None:
        app.config.update(config)
    
    # 왜 여기에서 import 를 하고 있을까요?
    # 맨 위로 옮기게 되면 어떻게 되나요? 어떤 잠재적 문제들이 있나요?
    from src.views.main_views import main_bp
    from src.views.user_views import user_bp

    app.register_blueprint(main_bp)
    app.register_blueprint(user_bp, url_prefix='/api')

    return app
    

src/views/main_views.py
import csv
import src.Part_1 as Part_1

from flask import Blueprint, render_template

main_bp = Blueprint('main', __name__)


@main_bp.route('/', methods=['GET'])
def index():
    """
    index 함수에서는 '/' 엔드 포인트로 접속했을 때 'index.html' 파일을
    렌더링 해줍니다.

    'index.html' 파일에서 'users.csv' 파일에 저장된 유저 목록을 보여줄 수 있도록
    유저들을 html 파일에 넘길 수 있어야 합니다.

    요구사항:
      - HTTP Method: `GET`
      - Endpoint: `/`

    상황별 요구사항:
      - `GET` 요청이 들어오면 `templates/index.html` 파일을 렌더 해야 합니다.

    """
 



    return render_template('index.html')  ## 이부분 잘 알아둘것 

src/views/user_views.py
import os
import csv
import json
import src.Part_1 as Part_1

from flask import Blueprint, request, render_template


user_bp = Blueprint('movie', __name__)



@user_bp.route('/movie', methods=['GET'])
def get_movie():
    
    movie_title = request.args.get('movie_title')

    Part_1.make_reviews(movie_title)

    score=list()
    info=dict()
    score=Part_1.get_score(movie_title)
    info=Part_1.get_info(movie_title)


    if movie_title == None:
      return "No movie title given", 400
    elif score != None:
      return render_template('index.html', score=score, info=info)
    else:
      return f"moive '{movie_title}' doesn't exist", 404

src/templates/index.html
<!DOCTYPE html>
<html>

  <head>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
  </head>
  <body>
    <div class="navbar navbar-dark bg-dark shadow-sm">
      <div class="container">
        <a href="#" class="navbar-brand d-flex align-items-center">
          <strong>Reveiw Decomposer</strong>
        </a>
      </div>
    </div>
    <section class="py-5 text-center container">
      <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
          <h1 class="fw-light">Review Decomposer Application</h1>
          <br>
          <p class="lead text-muted">
          Review Decomposer 어플리케이션 메인 페이지에 온 것을 환영합니다
          <br>
          영화 제목을 입력하면 리뷰를 감정분석하여 평점을 여러가지 요소로 분해하여 제공합니다.
          </p>
        </div>
      </div>
    </section>
    <section class="py-5 text-center container">
      
      <div class="jumbotron">
      <form action="{{url_for('movie.get_movie')}}">
      <label for="first">Movie title : </label>
      <input type="text" name="movie_title">

      <input class="btn btn-primary" type="submit" value="Submit Form">
      </form>
      </div>



      {% if score %}
        <div>
          <h1 class="fw-light">{{info["full_title"]}}</h1>
          <li>Origianl: {{score["Average"]}}</li>
          <li>HateSpeech:{{score["HateSpeech"]}} Count:{{score["HateSpeechnum"]}}</li>
          <li>Offensive:{{score["Offensive"]}} Count:{{score["Offensivenum"]}}</li>  
          <li>Pure:{{score["Pure"]}} Count:{{score["Purenum"]}}</li>
        </div>    
      {% endif %}


      {% if info %}
        <div>
          <h1 class="fw-light">info</h1>
          <li>Synopsis: {{info["synopsis"]}}</li>
          <li>tomatometerscore:{{info["tomatometerscore"]}}</li>
          <li>audiencescore:{{info["audiencescore"]}}</li>  
          <li>genre:{{info["genre"]}}</li>
          <li>director: {{info["director"]}}</li>
          <li>writer:{{info["writer"]}}</li>
          <li>theater_date:{{info["theater_date"]}}</li>  
          <li>dvd_date:{{info["dvd_date"]}}</li>
          <li>box_office: {{info["box_office"]}}</li>
          <li>runtime:{{info["runtime"]}}</li>
          <li>studio:{{info["studio"]}}</li>  
          <li>Collection:{{info["Collection"]}}</li>
        </div>    
      {% endif %}


    </section>
  </body>
</html>